# Generated by Django 3.1.5 on 2021-01-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='gyro_x',
        ),
        migrations.RemoveField(
            model_name='data',
            name='gyro_y',
        ),
        migrations.RemoveField(
            model_name='data',
            name='gyro_z',
        ),
    ]
